### ISSUE TITLE
ビルドしたeBook版の配布について

### ISSUE THREAD

**Issue by ryota-murakami** [dwango-js/performance-handbook#1]
こんにちは。

この度はニコニコ動画で実際に使われているテクニックの公開に踏み切って頂きありがとうございます。
まだ全てを読み切っておりませんが、現実的な観点での項目が多く非常に重宝する書籍であると感じております😀

個人的にeBookにしてiPadで読むのが好みなのでepubをビルドしたのですが、
[現行gitbookのドキュメント](https://toolchain.gitbook.com/ebook.html)に記載されているコマンドが最近のMacでは動作せず([修正PRを出したところです](https://github.com/GitbookIO/gitbook/pull/2122))、自身でのビルドに支障が出ている方も少数ながらいらっしゃるかと思い、
以下のページで成果物のepubをDL出来るようにしているのですがメンテナーさんの方針など踏まえ問題が無いか確認したく、Issueを建てさせて頂きました。

https://github.com/ryota-murakami/performance-handbook/releases

どうぞ宜しくお願いいたします🙇‍♂️

**Comment by azu** [comment]
ライセンスは[CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/deed.ja)であるため、再配布は問題ないと思いますね。

pdfやepubなどもあったほうが良さそうなので、ダウンロード版を追加するPR #2 を出してみました。
(別々にビルドすると差分が発生してしまうことがあるので、CI側で生成するような形がいいと思います。)

**Comment by azu** [comment]
マージされたので、各種ファイルをダウンロードできるようになったみたいです。

- [PDF版](https://dwango-js.github.io/performance-handbook/performance-handbook.pdf)
- [EPUB版](https://dwango-js.github.io/performance-handbook/performance-handbook.epub)
- [MOBI版](https://dwango-js.github.io/performance-handbook/performance-handbook.mobi)

**Comment by ryota-murakami** [comment]
おお、すごい！(埋め込み動画あったの知りませんでした)

再配布は停止しておきました、ありがとうございます😄
